node.id=presto-worker-2
coordinator=false
http-server.http.port=8080
discovery.uri=http://presto-coordinator:8080
experimental.spill-enabled=true
experimental.spiller-spill-path=/tmp/presto/spill
experimental.max-spill-per-node=10GB
experimental.query-max-spill-per-node=2GB
experimental.aggregation-spill-enabled=true
experimental.join-spill-enabled=true
query.max-memory-per-node=30MB
query.max-total-memory-per-node=150MB
